### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape' when starting the tft-bot

### ISSUE THREAD

**Issue by fittwitt** [Detergent13/tft-bot#54]
Here is the full output.
Developed by:

 _____       _                            _
|  __ \     | |                          | |
| |  | | ___| |_ ___ _ __ __ _  ___ _ __ | |_
| |  | |/ _ \ __/ _ \ '__/ _` |/ _ \ '_ \| __|
| |__| |  __/ ||  __/ | | (_| |  __/ | | | |_
|_____/ \___|\__\___|_|  \__, |\___|_| |_|\__|
                          __/ |
                         |___/

Welcome! You're running Detergent's TFT bot.
Please feel free to ask questions or contribute at https://github.com/Detergent13/tft-bot
Bot started, queuing up!
Traceback (most recent call last):
  File "C:\Users\gabby\Downloads\tft-bot-main\tft-bot-main\tft.py", line 205, in <module>
    queue()
  File "C:\Users\gabby\Downloads\tft-bot-main\tft-bot-main\tft.py", line 63, in queue
    if onscreen("./captures/tft logo.png"):
  File "C:\Users\gabby\Downloads\tft-bot-main\tft-bot-main\tft.py", line 22, in onscreen
    return search(path, precision)[0] != -1
  File "C:\ProgramData\Anaconda3\lib\site-packages\python_imagesearch\imagesearch.py", line 122, in imagesearch
    template.shape[::-1]
AttributeError: 'NoneType' object has no attribute 'shape'****

**Comment by fittwitt** [comment]
Setting the working directory to the correct folder fixed this issue.
