### ISSUE TITLE
Runnign error

### ISSUE THREAD

**Issue by RazvT** [Detergent13/tft-bot#89]
When I run this  =>  python "tft.py"

I receive the following error : ( installed manually all the requirements ( also installed with the `pip install -r requirements.txt`  )
![kk](https://user-images.githubusercontent.com/70648089/189544856-0d4a1b03-c1bb-4eec-a9c4-3eef21a52dfb.PNG)

Traceback (most recent call last):
  File "D:\Other\tft-bot-main\tft.py", line 10, in <module>
    pkg_resources.require("PyAutoGUI==0.9.50")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\pkg_resources\__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\pkg_resources\__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (PyAutoGUI 0.9.53 (c:\users\donttouchme\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages), Requirement.parse('PyAutoGUI==0.9.50'))

**Comment by jppuzzle** [comment]
Wild guess but you can try using python 3.8.3?

**Comment by Detergent13** [comment]
Yep, like @jppuzzle said, you have the wrong version of Python. Also the wrong version of PyAutoGUI. Either uninstall the wrong versions and install the right ones, or keep both and just make sure you're running the correct Python executable
